import { Asset } from '../../types/editor.types';

// ── 3D Social & Misc Stickers (YouTube, Like, Games, Neon, etc.) ─────
export const imageTpl3dObjectsB: Asset[] = [
    { "id": "img_yt_0",      "name": "3D YouTube Subscribe", "type": "image", "src": "/images/youtube_subscribe.webp",          "duration": 5.0, "thumbnail": "/images/youtube_subscribe.webp",          "templateData": { "properties": { "scale": 30, "positionX": 0,    "positionY": 300,  "rotation": 0   } } },
    { "id": "img_like_1",    "name": "3D Like Button",       "type": "image", "src": "/images/like_button.webp",                "duration": 5.0, "thumbnail": "/images/like_button.webp",                "templateData": { "properties": { "scale": 20, "positionX": 0,    "positionY": 0,    "rotation": -10 } } },
    { "id": "img_ctrl_2",    "name": "Neon Gaming Controller","type": "image", "src": "/images/gaming_controller.webp",          "duration": 5.0, "thumbnail": "/images/gaming_controller.webp",          "templateData": { "properties": { "scale": 50, "positionX": 0,    "positionY": 0,    "rotation": 0   } } },
    { "id": "img_arrow_3",   "name": "Neon Arrow Right",     "type": "image", "src": "/images/neon_arrow.webp",                 "duration": 5.0, "thumbnail": "/images/neon_arrow.webp",                 "templateData": { "properties": { "scale": 25, "positionX": -200, "positionY": 0,    "rotation": 0   } } },
    { "id": "img_star_4",    "name": "Golden Star",          "type": "image", "src": "/images/golden_star.webp",                "duration": 5.0, "thumbnail": "/images/golden_star.webp",                "templateData": { "properties": { "scale": 20, "positionX": 0,    "positionY": -300, "rotation": 0   } } },
    { "id": "img_bubble_5",  "name": "Comic Speech Bubble",  "type": "image", "src": "/images/speech_bubble.webp",              "duration": 5.0, "thumbnail": "/images/speech_bubble.webp",              "templateData": { "properties": { "scale": 40, "positionX": 200,  "positionY": -200, "rotation": 0   } } },
    { "id": "img_gift_6",    "name": "3D Gift Box",          "type": "image", "src": "/images/3d_gift_box_1779588058182.webp",   "duration": 5.0, "thumbnail": "/images/3d_gift_box_1779588058182.webp",   "templateData": { "properties": { "scale": 30, "positionX": -300, "positionY": 200,  "rotation": 0   } } },
    { "id": "img_crown_7",   "name": "3D Golden Crown",      "type": "image", "src": "/images/3d_crown_1779588072253.webp",      "duration": 5.0, "thumbnail": "/images/3d_crown_1779588072253.webp",      "templateData": { "properties": { "scale": 25, "positionX": 0,    "positionY": -300, "rotation": 10  } } },
    { "id": "img_mega_8",    "name": "3D Megaphone",         "type": "image", "src": "/images/3d_megaphone_1779588085402.webp",  "duration": 5.0, "thumbnail": "/images/3d_megaphone_1779588085402.webp",  "templateData": { "properties": { "scale": 20, "positionX": -200, "positionY": -200, "rotation": -15 } } },
    { "id": "img_shield_9",  "name": "Security Shield",      "type": "image", "src": "/images/3d_shield_1779588104233.webp",     "duration": 5.0, "thumbnail": "/images/3d_shield_1779588104233.webp",     "templateData": { "properties": { "scale": 25, "positionX": 300,  "positionY": 0,    "rotation": 0   } } },
    { "id": "img_heart_10",  "name": "Glowing Red Heart",    "type": "image", "src": "/images/3d_heart_1779588115849.webp",      "duration": 5.0, "thumbnail": "/images/3d_heart_1779588115849.webp",      "templateData": { "properties": { "scale": 20, "positionX": 0,    "positionY": 0,    "rotation": 0   } } },
    { "id": "img_bell_11",   "name": "Notification Bell",    "type": "image", "src": "/images/3d_bell_1779588127628.webp",       "duration": 5.0, "thumbnail": "/images/3d_bell_1779588127628.webp",       "templateData": { "properties": { "scale": 20, "positionX": 300,  "positionY": -300, "rotation": 15  } } },
    { "id": "img_warn_12",   "name": "Neon Warning",         "type": "image", "src": "/images/3d_warning_1779588145684.webp",    "duration": 5.0, "thumbnail": "/images/3d_warning_1779588145684.webp",    "templateData": { "properties": { "scale": 35, "positionX": -300, "positionY": 0,    "rotation": 0   } } },
    { "id": "img_target_13", "name": "Archery Target",       "type": "image", "src": "/images/3d_target_1779588156909.webp",     "duration": 5.0, "thumbnail": "/images/3d_target_1779588156909.webp",     "templateData": { "properties": { "scale": 30, "positionX": 200,  "positionY": 200,  "rotation": 0   } } },
    { "id": "img_camera_14", "name": "Vintage Camera",       "type": "image", "src": "/images/3d_camera_1779588172096.webp",     "duration": 5.0, "thumbnail": "/images/3d_camera_1779588172096.webp",     "templateData": { "properties": { "scale": 30, "positionX": 0,    "positionY": 200,  "rotation": 0   } } },
];
